spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:wethink.db
    username: postgres
    password: postgres
  mybatis:
    mapper-locations: classpath:com/example/wethink/dao/*.xml
    type-aliases-package: com.example.wethink.model
  mvc:
    view:
      prefix: static/
      suffix: index.html
server:
  port: 8081
